---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
    exclude_paths:
      - "tests/"
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
ratings:
  paths:
  - "**.py"
exclude_paths: []
